// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace ArvoreAbsorptionSystem
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "ArvoreAbsorptionSystem";
        public const string Version     = "1.0.0";
        public const string Title       = "Árvore Absorption System";
        public const string Description = "A complete, high-performance(?) rewrite of environmental tree absorption (Noise and Air) with custom mathematical curves.-- Reescrita completa e de alta performance da absorção ambiental de árvores (Ruído e Ar) com curvas matemáticas personalizáveis.";
    }
}
